version: '3.8'

services:
  nginx:
    image: nginx:alpine
    container_name: sales_nginx
    ports:
      - "8081:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - sales_network

  php:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    container_name: sales_php
    volumes:
      - ./:/var/www/html
    networks:
      - sales_network
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - postgres

  postgres:
    image: postgres:16-alpine
    container_name: sales_postgres
    restart: unless-stopped
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: sales_user
      POSTGRES_PASSWORD: sales_secret
      POSTGRES_DB: sales_system
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - sales_network

  npm:
    image: node:20-alpine
    container_name: sales_npm
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html
    ports:
      - "5173:5173"
    networks:
      - sales_network
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0"

networks:
  sales_network:
    driver: bridge

volumes:
  postgres_data:
